# Generated by Django 5.2.1 on 2025-05-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dump_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_type', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relative_path', models.CharField(blank=True, max_length=512, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.device')),
            ],
        ),
    ]
