# Generated by Django 5.2.1 on 2025-05-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('match_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.analysissession')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_matches', to='ingest.file')),
                ('target_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_matches', to='ingest.file')),
            ],
        ),
    ]
