# Generated by Django 5.2.1 on 2025-05-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matched_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
